version: "3"
services:
  nginx:
    depends_on:
      - backend
      - frontend
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "3000:80"
    networks:
      - local

  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    stdin_open: true
    networks:
      - local

  mysql:
    container_name: mysql
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: arch
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    networks:
      - local

  backend:
    depends_on:
      - mysql
    links:
      - mysql
    container_name: backend
    build:
      dockerfile: Dockerfile.dev2
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/api/app
    networks:
      - local

networks:
  local:
    driver: bridge