version: "3"
services:
  mysql:
    container_name: mysql
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: arch
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    networks:
      - local
  backend:
    links:
      - mysql
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/api/app
    networks:
      - local


networks:
  local:
    driver: bridge